package com.pio.skripsi.dfskripsi.dfs.model;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.IdentityScopeType;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tb_nodeDaoConfig;
    private final DaoConfig tb_relationDaoConfig;

    private final tb_nodeDao tb_nodeDao;
    private final tb_relationDao tb_relationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tb_nodeDaoConfig = daoConfigMap.get(tb_nodeDao.class).clone();
        tb_relationDaoConfig = daoConfigMap.get(tb_relationDao.class).clone();
        tb_nodeDaoConfig.initIdentityScope(type);
        tb_relationDaoConfig.initIdentityScope(type);

        tb_nodeDao = new tb_nodeDao(tb_nodeDaoConfig, this);
        tb_relationDao = new tb_relationDao(tb_relationDaoConfig, this);

        registerDao(tb_node.class, tb_nodeDao);
        registerDao(tb_relation.class, tb_relationDao);
    }
    
    public void clear() {
        tb_nodeDaoConfig.getIdentityScope().clear();
        tb_relationDaoConfig.getIdentityScope().clear();
    }

    public tb_nodeDao getTb_nodeDao() {
        return tb_nodeDao;
    }
    public tb_relationDao getTb_relationDao() {
        return tb_relationDao;
    }

}
