package com.pio.skripsi.dfskripsi.dfs.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table tb_relation.
 */
public class tb_relation {

    private String id_node;
    private String id_way;

    public tb_relation() {
    }

    public tb_relation(String id_node) {
        this.id_node = id_node;
    }

    public tb_relation(String id_node, String id_way) {
        this.id_node = id_node;
        this.id_way = id_way;
    }

    public String getId_node() {
        return id_node;
    }

    public void setId_node(String id_node) {
        this.id_node = id_node;
    }

    public String getId_way() {
        return id_way;
    }

    public void setId_way(String id_way) {
        this.id_way = id_way;
    }

}
